//! Tool project scaffolding.
//!
//! Generates a new Rust crate implementing the `Tool` trait,
//! ready to be compiled and loaded as a custom tool.

use std::fs;
use std::path::{Path, PathBuf};

/// Generate a new tool project at the given directory.
pub fn generate_tool_project(name: &str, output_dir: &Path) -> Result<PathBuf, String> {
    let project_dir = output_dir.join(name);

    if project_dir.exists() {
        return Err(format!(
            "Directory '{}' already exists. Choose a different name or remove it first.",
            project_dir.display()
        ));
    }

    let src_dir = project_dir.join("src");
    fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src/ directory: {e}"))?;

    // ── Cargo.toml ──────────────────────────────────────
    write_cargo_toml(&project_dir, name)?;

    // ── src/lib.rs ──────────────────────────────────────
    write_lib_rs(&src_dir, name)?;

    // ── README.md ──────────────────────────────────────
    write_readme(&project_dir, name)?;

    Ok(project_dir)
}

fn write_cargo_toml(project_dir: &Path, name: &str) -> Result<(), String> {
    let content = format!(
        r#"[package]
name = "code-agent-tool-{name}"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Custom tool for CraftCoder AI Coding Agent"

[dependencies]
code-agent-core = {{ version = "0.1.0" }}
code-agent-protocol = {{ version = "0.1.0" }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
async-trait = "0.1"
tokio = {{ version = "1", features = ["rt", "macros"] }}

[dev-dependencies]
tempfile = "3"

[lib]
crate-type = ["cdylib", "rlib"]
"#
    );

    let path = project_dir.join("Cargo.toml");
    fs::write(&path, content)
        .map_err(|e| format!("Failed to write Cargo.toml: {e}"))?;
    Ok(())
}

fn write_lib_rs(src_dir: &Path, name: &str) -> Result<(), String> {
    let struct_name = to_pascal_case(name);
    let tool_name = name.replace('_', "-");

    let content = format!(
        r#"//! Custom tool `{tool_name}` for CraftCoder AI Coding Agent.
//!
//! This file was generated by `code-agent tool new {name}`.
//! Replace the TODO comment in `execute()` with your tool logic.

use async_trait::async_trait;
use code_agent_protocol::{{CapabilityLevel, ToolResultMessage}};
use code_agent_core::tools::{{require_string, optional_string, tool_error, tool_success, Tool, ToolError}};

/// {struct_name} tool — TODO: add a brief description of what your tool does.
pub struct {struct_name};

impl Default for {struct_name} {{
    fn default() -> Self {{
        Self
    }}
}}

#[async_trait]
impl Tool for {struct_name} {{
    fn name(&self) -> &str {{
        "{tool_name}"
    }}

    fn description(&self) -> &str {{
        // TODO: Write a clear description that helps the LLM choose this tool.
        // Keep it under 200 characters. Mention when to use and what it returns.
        "Performs {tool_name} operations. TODO: replace with actual description."
    }}

    fn input_schema(&self) -> serde_json::Value {{
        serde_json::json!({{
            "type": "object",
            "properties": {{
                "input": {{
                    "type": "string",
                    "description": "The input value for this tool"
                }}
            }},
            "required": ["input"]
        }})
    }}

    fn capability(&self) -> CapabilityLevel {{
        // Read: only reads files/data. Edit: modifies files. Exec: runs commands.
        CapabilityLevel::Read
    }}

    async fn execute(
        &self,
        params: serde_json::Value,
    ) -> Result<ToolResultMessage, ToolError> {{
        let input = require_string(&params, "input")?;

        // ── TODO: Replace with your tool logic ─────────────────────
        // Use these helpers:
        //   - require_string(&params, "key") → extract required string
        //   - optional_string(&params, "key") → extract optional string
        //   - optional_u64(&params, "key") → extract optional number
        //   - tool_success("", output) → build success response
        //   - tool_error("", reason) → build error response
        //
        // For file operations, use resolve_safe_path for security:
        //   - code_agent_core::tools::resolve_safe_path(&path)?
        //   - code_agent_core::tools::resolve_safe_path_create(&path)?
        // ──────────────────────────────────────────────────────────

        Ok(tool_success("", format!("Processed: {{input}}")))
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;
    use serde_json::json;

    #[tokio::test]
    async fn test_{name}_basic_execution() {{
        let tool = {struct_name}::default();

        // Verify metadata
        assert_eq!(tool.name(), "{tool_name}");
        assert!(!tool.description().is_empty());
        assert!(tool.capability() == CapabilityLevel::Read);

        // Test input schema has required fields
        let schema = tool.input_schema();
        let required = schema["required"].as_array().unwrap();
        assert!(required.iter().any(|v| v.as_str() == Some("input")));

        // Test execution
        let params = json!({{"input": "hello"}});
        let result = tool.execute(params).await.expect("should succeed");
        assert!(result.is_success());
        assert!(result.output.unwrap().contains("hello"));
    }}

    #[tokio::test]
    async fn test_{name}_missing_input() {{
        let tool = {struct_name}::default();
        let params = json!({{}});
        let result = tool.execute(params).await;
        assert!(result.is_err());
    }}
}}
"#
    );

    let path = src_dir.join("lib.rs");
    fs::write(&path, content)
        .map_err(|e| format!("Failed to write src/lib.rs: {e}"))?;
    Ok(())
}

fn write_readme(project_dir: &Path, name: &str) -> Result<(), String> {
    let content = format!(
        r#"# code-agent-tool-{name}

Custom tool for [CraftCoder](https://github.com/anrror/CraftCoder) AI Coding Agent.

Generated by `code-agent tool new {name}`.

## Building

```bash
cargo build --release
```

## Loading into CraftCoder

Add to your `config.toml`:

```toml
[mcp_servers.{name}]
command = "target/release/code-agent-tool-{name}"
```

Or load programmatically:

```rust
use code_agent_core::tools::registry::DefaultToolRegistry;
use std::sync::Arc;

let mut registry = DefaultToolRegistry::new();
registry.register(Arc::new(
    code_agent_tool_{name}::{struct_name}::default()
)).expect("register tool");
```

## Testing

```bash
cargo test
```
"#,
        struct_name = to_pascal_case(name),
        name = name,
    );

    let path = project_dir.join("README.md");
    fs::write(&path, content)
        .map_err(|e| format!("Failed to write README.md: {e}"))?;
    Ok(())
}

/// Convert snake_case to PascalCase.
fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pascal_case() {
        assert_eq!(to_pascal_case("web_search"), "WebSearch");
        assert_eq!(to_pascal_case("slack_notify"), "SlackNotify");
        assert_eq!(to_pascal_case("hello"), "Hello");
        assert_eq!(to_pascal_case("a_b_c"), "ABC");
    }

    #[test]
    fn test_generate_and_verify() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let project = generate_tool_project("my_test_tool", tmp.path())
            .expect("generate should succeed");

        assert!(project.join("Cargo.toml").exists());
        assert!(project.join("src/lib.rs").exists());
        assert!(project.join("README.md").exists());

        // Verify Cargo.toml content
        let cargo_toml = std::fs::read_to_string(project.join("Cargo.toml")).unwrap();
        assert!(cargo_toml.contains("code-agent-tool-my_test_tool"));
        assert!(cargo_toml.contains("code-agent-core"));

        // Verify lib.rs content
        let lib_rs = std::fs::read_to_string(project.join("src/lib.rs")).unwrap();
        assert!(lib_rs.contains("struct MyTestTool"));
        assert!(lib_rs.contains("\"my-test-tool\""));
        assert!(lib_rs.contains("impl Tool for MyTestTool"));
    }

    #[test]
    fn test_duplicate_project_rejected() {
        let tmp = tempfile::tempdir().expect("tempdir");
        generate_tool_project("dup", tmp.path()).expect("first should pass");
        let result = generate_tool_project("dup", tmp.path());
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("already exists"));
    }
}
